---
name: Analysis - Review Dog

on:
  pull_request:

jobs:

  cppcheck:
    runs-on: ubuntu-latest
    steps:

      - name: Check out code.
        uses: actions/checkout@master

      - name: Setup reviewdog
        uses: reviewdog/action-setup@v1

      - name: Setup cppcheck
        run: sudo apt-get update && sudo apt-get install -y cppcheck

      - name: cppcheck
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd $GITHUB_WORKSPACE
          cppcheck --version
          reviewdog -reporter=github-pr-check -runners=cppcheck


  luac:
    runs-on: ubuntu-latest
    steps:

      - name: Check out code.
        uses: actions/checkout@master

      - name: Setup reviewdog
        uses: reviewdog/action-setup@v1

      - name: Setup Lua/Luacheck
        run: sudo apt-get update && sudo apt-get install -y lua5.1 liblua5.1-0-dev lua-check

      - name: luac
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd $GITHUB_WORKSPACE
          luac -v
          reviewdog -reporter=github-pr-check -runners=luac


  luacheck:
    runs-on: ubuntu-latest
    steps:

      - name: Check out code.
        uses: actions/checkout@master

      - name: Setup reviewdog
        uses: reviewdog/action-setup@v1

      - name: Setup Lua/Luacheck
        run: sudo apt-get update && sudo apt-get install -y lua5.1 liblua5.1-0-dev lua-check

      - name: luacheck
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          luacheck --version
          cd $GITHUB_WORKSPACE
          reviewdog -reporter=github-pr-check -runners=luacheck


  shellcheck:
    runs-on: ubuntu-latest
    steps:

      - name: Check out code.
        uses: actions/checkout@master

      - name: shellcheck
        uses: reviewdog/action-shellcheck@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-check
          pattern: '*.sh'
          exclude: './.git/*'


  xmllint:
    runs-on: ubuntu-latest
    steps:

      - name: Check out code.
        uses: actions/checkout@master

      - name: Setup reviewdog
        uses: reviewdog/action-setup@v1

      - name: Setup xmllint
        run: sudo apt-get update && sudo apt-get install -y libxml2-utils

      - name: xmllint
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd $GITHUB_WORKSPACE
          xmllint --version
          reviewdog -reporter=github-pr-check -runners=xmllint


  yamllint:
    runs-on: ubuntu-latest
    steps:

      - name: Check out code.
        uses: actions/checkout@master

      - name: Run yamllint
        uses: reviewdog/action-yamllint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-check


  hadolint:
    runs-on: ubuntu-latest
    steps:

      - name: Check out code
        uses: actions/checkout@master

      - name: hadolint
        uses: reviewdog/action-hadolint@v1
        with:
          reporter: github-pr-check
